### ISSUE TITLE
Software Version 8.0.0 compatibility 

### ISSUE THREAD

**Issue by MichaelLiZhou** [kevinsteves/pan-python#15]
Is there any reason for this library would not be compatible with latest update in SW version 8? When I try to generate a .panrc file an error shows up:

`keygen: "URLError: reason: EOF occurred in violation of protocol (_ssl.c:645)"`

Is there a REST equivalent to:

`panxapi.py -t pan-python -h xx.xx.xx.xx -l xxxx -k`

**Comment by kevinsteves** [comment]
This is caused by the removal of TLSv1.0 from the default allowed SSL management protocols in 8.0 and documented here:

https://www.paloaltonetworks.com/documentation/80/pan-os/pan-os-release-notes/pan-os-8-0-release-information/changes-to-default-behavior#19035

You can configure a SSL/TLS service profile as described to address.

Alternatively, the underlying cause may be your Python is not built with an OpenSSL version which supports TLSv1,[12].  You will need a version >= 1.0.1.

You can determine your OpenSSL version with:

`$ python -c 'import ssl;print ssl.OPENSSL_VERSION'`
`OpenSSL 0.9.8zg 14 July 2015`

**Comment by kevinsteves** [comment]
I made this change to pan.xapi:

When URLError try to deduce if it's a SSL handshake error and if
OpenSSL may not support TLS 1.1, and log warning at debug1 that PAN-OS
8.0 does not allow TLS 1.0 connections by default.
